### ISSUE TITLE
去除无效的import吧！

### ISSUE THREAD

**Issue by gityu2013** [beecloud/beecloud-java#21]
BCPayParameter 类 
     import cn.beecloud.BCEumeration;
BCRefundBean 类
     import java.util.HashMap;
     import java.util.Map;
并没有被用上

虽然没有什么影响，但是这个不是因为注释掉了东西暂时不用，还是不要导入吧，看着难受。

**Comment by quietbamboo** [comment]
同意 @figo10203

**Comment by figo10203** [comment]
多谢宝贵意见！

**Comment by quietbamboo** [comment]
先开一下   等 @figo10203 fix了，再close，免得忘记了

**Comment by figo10203** [comment]
已fix.谢谢！
