### ISSUE TITLE
Test mode和Live mode应该区分开

### ISSUE THREAD

**Issue by quietbamboo** [beecloud/beecloud-java#29]
BeeCloud.registerApp(appId, testSecret, appSecret, masterSecret);

这个函数的设计很差，test mode和 live mode不应该混用一个函数。而且改变了函数接口，不具有与v2.3.0的向前兼容性

事实上只需要两个函数：
BeeCloud.registerApp(appId, appSecret, masterSecret);  这个函数就是调用了live mode，和v2.3.0里面的这个函数一模一样

还需要
BeeCloud.registerAppTestMode(appId, testSecret, masterSecret);
用了这个函数就是test mode。

**Comment by figo10203** [comment]
Hi  Jim, 这个版本的改动比较大，接口参数都变了，开发者调用所有的接口都会要重写，注册那个地方传4个参数也可看作是重写，个人觉得此处不需要考虑太多向前兼容。  而且注册一次，通过BeeCloud.setSandbox(true)控制室沙箱模式还是LIVE模式比较清晰，两次注册，再调用BeeCloud.setSandbox()方法，开发者可能会混淆开启沙箱模式到底是以BeeCloud.registerAppTestMode(appId, testSecret, masterSecret)还是BeeCloud.setSandbox为准。
你觉得呢

**Comment by quietbamboo** [comment]
我的意思是用了BeeCloud.registerAppTestMode(appId, testSecret, masterSecret)，就不需要BeeCloud.setSandbox()这个方法了。不过你说的也有道理，因为用BeeCloud.registerAppTestMode的话，需要和BeeCloud.registerApp互斥，否则会比较麻烦。 那么就按照你现在的设计来吧。不过readme貌似没更新？ 因为我没看到readme里有setSandbox这个函数的介绍
