### ISSUE TITLE
Test mode文档

### ISSUE THREAD

**Issue by quietbamboo** [beecloud/beecloud-java#30]
请在README里加上test mode的文档

**Comment by quietbamboo** [comment]
我看到了，不过文档结构有些问题。

是Live mode还是test mode，我觉得是在top level里面需要介绍的。比如在最前面

**Comment by quietbamboo** [comment]
在“LIVE模式使用方法”  后面就写"Sandbox模式使用方法“，不要距离太远。

**Comment by figo10203** [comment]
已改
