### ISSUE TITLE
这里两次调用是不是有什么原因，还是失误

### ISSUE THREAD

**Issue by dhhua** [beecloud/beecloud-java#42]
![image](https://cloud.githubusercontent.com/assets/10860809/14016577/80b8c878-f1fc-11e5-9432-cb4639b522ad.png)

**Comment by sayMeFat** [comment]
请问如果在.java代码中写Webhook回调，out.println("success")，应该怎么写？System.out.println("success")？response.getWriter().write("success")？还是别的？ @dhhua

**Comment by dhhua** [comment]
response.getWriter().println(“success");
反正就是给相应的输出流返回一个success字符串吧
spring mvc可以这样
@RequestMapping("notify")
@ResponseBody
public String notifyUrl(){
return "success"
}

你基础不好吧，得努力学习下，起码了解jsp的九大内置对象，学习下servlet的原理 @sayMeFat

**Comment by sayMeFat** [comment]
谢谢啊，光知道用了，基础有待提高

**Comment by figo10203** [comment]
@dhhua, 已删除重复的代码，已发布修改，感谢你的建议
