### ISSUE TITLE
验证webhook超时

### ISSUE THREAD

**Issue by pengbs** [beecloud/beecloud-java#80]
为什么我发送webhook测试的时候sign能匹配上，就是timeDifference总是大于300000

**Comment by quietbamboo** [comment]
可能你的服务器时间不对。可以再后台忽略时间校验

**Comment by pengbs** [comment]
嗯，好的，感谢，微信支付的能收到hook消息吗？我看文档说还要自己轮询？

**Comment by lacusrinz** [comment]
所有的渠道支付成功都有webhook，文档说的轮询是指前端的同步回调没有，需要自己查询来完成后面的逻辑

**Comment by pengbs** [comment]
嗯，明白了，非常感谢
